### PR TITLE
fix: routed section event to event detail page

### LINKED ISSUE #788: route  section event to particular event
**Describe the bug**
route  section event to particular event

### PR DESCRIPTION
**Pull request by kunwar-11**
# Pull Request Template

## Description

route section event to event detail page

Fixes #788 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

File: pages/index.js [hunk 1]
```diff
@@ -32,32 +32,32 @@ export async function getServerSideProps(context) {
...
       order: "ASC",
-      limit: 1,
       status: "published",
-      page: 1,
-      with_table: "users, tags"
+      page: 1
     };
     const responseEvents = await EventService.getLatestEvents(eventParams);
-    console.log(responseEvents, 'events');
+    console.log(responseEvents, "events");
```
Comment (jasirtp) [inline pages/index.js:40]: remove all comsole

**Comment by kunwar-11** [comment]
removed

**Review by jasirtp — APPROVED** [review]
