### PR TITLE
819/fix added event filter

### LINKED ISSUE #819: filter event via status and allow admin to change status for event
**Describe the bug**
filter event via status and allow admin to change the status for the event

### PR DESCRIPTION
**Pull request by kunwar-11**
# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #819 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

File: pages/admin/events/index.js [hunk 1]
```diff
@@ -112,13 +112,14 @@ const Admin = () => {
...
-      console.log(eventdata)
+      if (data.data) {
+        const { events, count } = data.data;
+        setEventdata((prev) => ({ ...prev, events, count }));
+      } else if (data.message === "Events not Found") {
+        setEventdata((prev) => ({ ...prev, events: [], count: 0 }));
       }
     } catch (err) {
-      console.log(err, 'error')
+      console.log(err, "error");
```
Comment (jasirtp) [inline pages/admin/events/index.js]: remove
