### PR TITLE
fix: fixed toast message when already signed up user try to sign up a…

### LINKED ISSUE #357: Signing up of already registered user, displayed incorrect Toast messages from backend, when tried to Signed up again
Signing up of already registered user, displayed incorrect Toast messages from backend, when tried to Signed up again.

**Steps To Reproduce**
1. Go to https://test-app.nullcast.dev/
2. Enter the credentials of an already registered user in the Sign up Form
3. User is displayed an incorrect Toast messages from backend

**Expected behavior**
Already registered User when signing up, has to view proper Toast message -- according to already used username or Email

**Screenshot attached**
Screenshot at 2021-11-02 09-49-40

**Desktop (please complete the following information):** ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)
**Smartphone:** not tested

**Additional context**
Tested in test site

### PR DESCRIPTION
**Pull request by kunwar-11**
# Pull Request Template

## Description

fixed toast message when already signed up user try to sign up again

Fixes #357 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

File: pages/signup.js [hunk 1]
```diff
@@ -178,7 +178,9 @@ export default function SignUp({ referer }) {
             }
           } catch (err) {
             setIsLoading(false);
-            notify(err?.response?.data?.message ?? err?.message, 'error');
+            let errorMessage = err?.response?.data?.message.split('"')[1] === 'users_email_key' ? "email already exists" : "username not available"
```
Comment (thealpha93) [inline pages/signup.js:181]: use `const` instead of `let`

File: pages/signup.js [hunk 2]
```diff
@@ -178,7 +178,9 @@ export default function SignUp({ referer }) {
...
+            console.log(errorMessage)
+            notify(err?.response?.data?.message && errorMessage, 'error');
```
Comment (thealpha93) [inline pages/signup.js:183]: No further need to check if `err?.response?.data?.message` exists

**Review by thealpha93 — CHANGES_REQUESTED** [review]

**Comment by kunwar-11** [comment]
made the asked changes
