### PR TITLE
fix: name changed in popup when user updates the profile

### LINKED ISSUE #607: Changes in the name of the user not getting reflected in the Avatar icon popover of the user
Changes in the name of the user not getting reflected in the Avatar icon popover of the user

**Steps To Reproduce**
1. Go to https://test-app.nullcast.dev
2. User gets redirected to the Homepage of Nullcast.
3. Click on the Login button
4. Enter the credentials and click on the Avatar icon where user gets navigated to the Profile page
5. Click on the "Settings" option from the menu of the Avatar popover
6. User navigates to the Settings-Profile page
7. In the Settings-Profile page, change the name of the user
8. But user could notice that, Changes in the name of the user not getting reflected in the Avatar icon popover of the user

**Expected behavior**
Changes in the name of the user not getting reflected in the Avatar icon popover of the user
**Screenshot attached**
Desktop (please complete the following information): ThinkPad
OS: Linux
Browser: Google Chrome
Version: Version 95.0.4638.54 (Official Build) (64-bit)

**Additional context**
Tested in Testsite

### PR DESCRIPTION
**Pull request by kunwar-11**
# Pull Request Template

## Description

name changed in popup when user updates the profiles fixed.

Fixes #607 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

File: component/layout/Profile/Profile.js [hunk 1]
```diff
@@ -2,13 +2,13 @@ import styles from "./Profile.module.scss";
...
 
-export default function Profile({ onLogout, username }) {
+export default function Profile({ onLogout, userName }) {
 
   // Retrieving userdata from session storage which is in string format
   // const userData = JSON.parse(sessionStorage.getItem("userNullcast"));
 	const cookies = new Cookies();
   const userCookie = cookies.get("userNullcast");
-
+  console.log(userCookie , 'profile')
```
Comment (sNkr-10) [inline component/layout/Profile/Profile.js:11]: Remove all console logs

File: pages/settings.js [hunk 2]
```diff
@@ -113,8 +114,15 @@ export default function Settings({ profileData, _skills }) {
       const response = await UserService.updateProfileByUserId(
         userCookie, profileData
       );
-      notify(response.message);
-      setLoading(false);
+      console.log(response)
```
Comment (sNkr-10) [inline pages/settings.js:117]: remove console log
